name: 'Install'
description: 'Install and pre-build'

runs:
  using: composite
  steps:
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        registry-url: 'https://registry.npmjs.org'

    - name: install yarn
      shell: bash
      run: npm i yarn -g

    - name: Install npm
      shell: bash
      run: npm i -g npm@10.8.2

    - name: Install corepack
      shell: bash
      run: corepack enable && corepack prepare yarn@4.4.1 --activate

    - name: Cache node_modules
      uses: actions/cache@v4
      env:
        cache-name: node_modules
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-
        save-always: true

    - name: Install Dependencies
      shell: bash
      run: yarn install

    - name: Clean Build
      shell: bash
      run: yarn clean:build

    - name: Build
      shell: bash
      run: yarn build
