name: Native Integration Tests

on:
  push:
  pull_request:

jobs:
  build-ios-test-dev-container:
    name: Build iOS Test Development Container App
    uses: ./.github/workflows/build-ios-test-dev-container.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: read
    # with:

  test-maestro:
    needs:
      - build-ios-test-dev-container
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hello World
        env:
          BUILD_HASH: ${{ needs.build-ios-test-dev-container.outputs.build-hash }}
        run: echo "Build hash is $BUILD_HASH"

      - name: Download Dev Container App
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          key: ${{ needs.build-ios-test-dev-container.outputs.built-app-cache-key }}
          path: ${{ needs.build-ios-test-dev-container.outputs.built-app-path }}

      - name: Hello World 2
        run: ls -al ${{ needs.build-ios-test-dev-container.outputs.built-app-path }}

      - name: Get Simulator UDID
        id: get-simulator-udid
        run: |
          SIMULATOR_INFO=$(xcrun simctl list devices available --json | jq '.devices."com.apple.CoreSimulator.SimRuntime.iOS-17-5" | map(select(.name | test("iPhone"))) | last')
          SIMULATOR_UDID=$(echo $SIMULATOR_INFO | jq -r .udid)
          echo "Simulator info: $SIMULATOR_INFO"
          echo "Simulator UDID: $BUILD_HASH"
          echo "simulator_udid=$SIMULATOR_UDID" >> $GITHUB_OUTPUT
      - name: Boot Simulator
        env:
          SIMULATOR_UDID: ${{ steps.get-simulator-udid.outputs.simulator_udid }}
        run: xcrun simctl boot $SIMULATOR_UDID
      - name: Boot Simulator
        env:
          SIMULATOR_UDID: ${{ steps.get-simulator-udid.outputs.simulator_udid }}
        run: xcrun simctl boot $SIMULATOR_UDID
      - name: Install Dev Container App in Simulator
        env:
          SIMULATOR_UDID: ${{ steps.get-simulator-udid.outputs.simulator_udid }}
          APP_PATH: ${{ needs.build-ios-test-dev-container.outputs.built-app-path }}
        working-directory: .
        run: xcrun simctl install $SIMULATOR_UDID $APP_PATH
      # - name: Install
      #   uses: ./.github/actions/install

