name: Native Integration Tests

on:
  push:
  pull_request:

jobs:
  build-ios-test-dev-container:
    name: Build iOS Test Development Container App
    uses: ./.github/workflows/build-ios-test-dev-container.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: read
    # with:

  test-maestro:
    needs:
      - build-ios-test-dev-container
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hello World
        env:
          BUILD_HASH: ${{ needs.build-ios-test-dev-container.outputs.build-hash }}
        run: echo "Build hash is $BUILD_HASH"

      - name: Download Dev Container App
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          key: ${{ needs.build-ios-test-dev-container.outputs.built-app-cache-key }}
          path: ${{ needs.build-ios-test-dev-container.outputs.built-app-path }}

      - name: Hello World 2
        run: ls -al ${{ needs.build-ios-test-dev-container.outputs.built-app-path }}

      # - name: Install
      #   uses: ./.github/actions/install

